tags = [
    "9F01",
    "9F40",
    "81",
    "9F02",
    "9F04",
    "9F03",
    "9F3A",
    "9F26",
    "9F42",
    "9F44",
    "9F05",
    "5F25",
    "5F24",
    "94",
    "4F",
    "9F06",
    "82",
    "50",
    "9F12",
    "5A",
    "5F34",
    "87",
    "9F3B",
    "9F43",
    "61",
    "9F36",
    "9F07",
    "9F08",
    "9F09",
    "89",
    "8A",
    "5F54",
    "8C",
    "8D",
    "5F20",
    "9F0B",
    "8E",
    "9F34",
    "8F",
    "9F22",
    "83",
    "9F27",
    "9F45",
    "84",
    "9D",
    "73",
    "9F49",
    "70",
    "BF0C",
    "A5",
    "6F",
    "9F4C",
    "9F2D",
    "9F2E",
    "9F2F",
    "9F46",
    "9F47",
    "9F48",
    "9F1E",
    "5F53",
    "9F0D",
    "9F0E",
    "9F0F",
    "9F10",
    "91",
    "9F11",
    "5F28",
    "5F55",
    "5F56",
    "42",
    "90",
    "9F32",
    "92",
    "86",
    "9F18",
    "71",
    "72",
    "5F50",
    "5F2D",
    "9F13",
    "9F4D",
    "9F4F",
    "9F14",
    "9F15",
    "9F16",
    "9F4E",
    "9F17",
    "9F39",
    "9F38",
    "80",
    "77",
    "5F30",
    "88",
    "9F4B",
    "93",
    "9F4A",
    "9F33",
    "9F1A",
    "9F1B",
    "9F1C",
    "9F1D",
    "9F35",
    "95",
    "9F1F",
    "9F20",
    "57",
    "98",
    "97",
    "5F2A",
    "5F36",
    "9A",
    "99",
    "9F3C",
    "9F3D",
    "9F41",
    "9B",
    "9F21",
    "9C",
    "9F37",
    "9F23"]

msgs = [
    "Acquirer Identifier",
    "Additional Terminal Capabilities",
    "Amount, Authorised (Binary)",
    "Amount, Authorised (Numeric)",
    "Amount, Other (Binary)",
    "Amount, Other (Numeric)",
    "Amount, Reference Currency",
    "Application Cryptogram",
    "Application Currency Code",
    "Application Currency Exponent",
    "Application Discretionary Data",
    "Application Effective Date",
    "Application Expiration Date",
    "Application File Locator (AFL)",
    "Application Identifier (AID) – card",
    "Application Identifier (AID) – terminal",
    "Application Interchange Profile",
    "Application Label",
    "Application Preferred Name",
    "Application Primary Account Number (PAN)",
    "Application Primary Account Number (PAN) Sequence Number",
    "Application Priority Indicator",
    "Application Reference Currency",
    "Application Reference Currency Exponent",
    "Application Template",
    "Application Transaction Counter (ATC)",
    "Application Usage Control",
    "Application Version Number",
    "Application Version Number",
    "Authorisation Code",
    "Authorisation Response Code",
    "Bank Identifier Code (BIC)",
    "Card Risk Management Data Object List 1 (CDOL1)",
    "Card Risk Management Data Object List 2 (CDOL2)",
    "Cardholder Name",
    "Cardholder Name Extended",
    "Cardholder Verification Method (CVM) List",
    "Cardholder Verification Method (CVM) Results",
    "Certification Authority Public Key Index",
    "Certification Authority Public Key Index",
    "Command Template",
    "Cryptogram Information Data",
    "Data Authentication Code",
    "Dedicated File (DF) Name",
    "Directory Definition File (DDF) Name",
    "Directory Discretionary Template",
    "Dynamic Data Authentication Data Object List (DDOL)",
    "EMV Proprietary Template",
    "File Control Information (FCI) Issuer Discretionary Data",
    "File Control Information (FCI) Proprietary Template",
    "File Control Information (FCI) Template",
    "ICC Dynamic Number",
    "Integrated Circuit Card (ICC) PIN Encipherment Public Key Certificate",
    "Integrated Circuit Card (ICC) PIN Encipherment Public Key Exponent",
    "Integrated Circuit Card (ICC) PIN Encipherment Public Key Remainder",
    "Integrated Circuit Card (ICC) Public Key Certificate",
    "Integrated Circuit Card (ICC) Public Key Exponent",
    "Integrated Circuit Card (ICC) Public Key Remainder",
    "Interface Device (IFD) Serial Number",
    "International Bank Account Number (IBAN)",
    "Issuer Action Code – Default",
    "Issuer Action Code – Denial",
    "Issuer Action Code – Online",
    "Issuer Application Data",
    "Issuer Authentication Data",
    "Issuer Code Table Index",
    "Issuer Country Code",
    "Issuer Country Code (alpha2 format)",
    "Issuer Country Code (alpha3 format)",
    "Issuer Identification Number (IIN)",
    "Issuer Public Key Certificate",
    "Issuer Public Key Exponent",
    "Issuer Public Key Remainder",
    "Issuer Script Command",
    "Issuer Script Identifier",
    "Issuer Script Template 1",
    "Issuer Script Template 2",
    "Issuer URL",
    "Language Preference",
    "Last Online Application Transaction Counter (ATC) Register",
    "Log Entry",
    "Log Format",
    "Lower Consecutive Offline Limit",
    "Merchant Category Code",
    "Merchant Identifier",
    "Merchant Name and Location",
    "Personal Identification Number (PIN) Try Counter",
    "Point-of-Service (POS) Entry Mode",
    "Processing Options Data Object List (PDOL)",
    "Response Message Template Format 1",
    "Response Message Template Format 2",
    "Service Code",
    "Short File Identifier (SFI)",
    "Signed Dynamic Application Data",
    "Signed Static Application Data",
    "Static Data Authentication Tag List",
    "Terminal Capabilities",
    "Terminal Country Code",
    "Terminal Floor Limit",
    "Terminal Identification",
    "Terminal Risk Management Data",
    "Terminal Type",
    "Terminal Verification Results",
    "Track 1 Discretionary Data",
    "Track 2 Discretionary Data",
    "Track 2 Equivalent Data",
    "Transaction Certificate (TC) Hash Value",
    "Transaction Certificate Data Object List (TDOL)",
    "Transaction Currency Code",
    "Transaction Currency Exponent",
    "Transaction Date",
    "Transaction Personal Identification Number (PIN) Data",
    "Transaction Reference Currency Code",
    "Transaction Reference Currency Exponent",
    "Transaction Sequence Counter",
    "Transaction Status Information",
    "Transaction Time",
    "Transaction Type",
    "Unpredictable Number",
    "Upper Consecutive Offline Limit"]


urls = [
    "https://emvlab.org/emvtags/show/t9F01/",
    "https://emvlab.org/emvtags/show/t9F40/",
    "https://emvlab.org/emvtags/show/t81/",
    "https://emvlab.org/emvtags/show/t9F02/",
    "https://emvlab.org/emvtags/show/t9F04/",
    "https://emvlab.org/emvtags/show/t9F03/",
    "https://emvlab.org/emvtags/show/t9F3A/",
    "https://emvlab.org/emvtags/show/t9F26/",
    "https://emvlab.org/emvtags/show/t9F42/",
    "https://emvlab.org/emvtags/show/t9F44/",
    "https://emvlab.org/emvtags/show/t9F05/",
    "https://emvlab.org/emvtags/show/t5F25/",
    "https://emvlab.org/emvtags/show/t5F24/",
    "https://emvlab.org/emvtags/show/t94/",
    "https://emvlab.org/emvtags/show/t4F/",
    "https://emvlab.org/emvtags/show/t9F06/",
    "https://emvlab.org/emvtags/show/t82/",
    "https://emvlab.org/emvtags/show/t50/",
    "https://emvlab.org/emvtags/show/t9F12/",
    "https://emvlab.org/emvtags/show/t5A/",
    "https://emvlab.org/emvtags/show/t5F34/",
    "https://emvlab.org/emvtags/show/t87/",
    "https://emvlab.org/emvtags/show/t9F3B/",
    "https://emvlab.org/emvtags/show/t9F43/",
    "https://emvlab.org/emvtags/show/t61/",
    "https://emvlab.org/emvtags/show/t9F36/",
    "https://emvlab.org/emvtags/show/t9F07/",
    "https://emvlab.org/emvtags/show/t9F08/",
    "https://emvlab.org/emvtags/show/t9F09/",
    "https://emvlab.org/emvtags/show/t89/",
    "https://emvlab.org/emvtags/show/t8A/",
    "https://emvlab.org/emvtags/show/t5F54/",
    "https://emvlab.org/emvtags/show/t8C/",
    "https://emvlab.org/emvtags/show/t8D/",
    "https://emvlab.org/emvtags/show/t5F20/",
    "https://emvlab.org/emvtags/show/t9F0B/",
    "https://emvlab.org/emvtags/show/t8E/",
    "https://emvlab.org/emvtags/show/t9F34/",
    "https://emvlab.org/emvtags/show/t8F/",
    "https://emvlab.org/emvtags/show/t9F22/",
    "https://emvlab.org/emvtags/show/t83/",
    "https://emvlab.org/emvtags/show/t9F27/",
    "https://emvlab.org/emvtags/show/t9F45/",
    "https://emvlab.org/emvtags/show/t84/",
    "https://emvlab.org/emvtags/show/t9D/",
    "https://emvlab.org/emvtags/show/t73/",
    "https://emvlab.org/emvtags/show/t9F49/",
    "https://emvlab.org/emvtags/show/t70/",
    "https://emvlab.org/emvtags/show/tBF0C/",
    "https://emvlab.org/emvtags/show/tA5/",
    "https://emvlab.org/emvtags/show/t6F/",
    "https://emvlab.org/emvtags/show/t9F4C/",
    "https://emvlab.org/emvtags/show/t9F2D/",
    "https://emvlab.org/emvtags/show/t9F2E/",
    "https://emvlab.org/emvtags/show/t9F2F/",
    "https://emvlab.org/emvtags/show/t9F46/",
    "https://emvlab.org/emvtags/show/t9F47/",
    "https://emvlab.org/emvtags/show/t9F48/",
    "https://emvlab.org/emvtags/show/t9F1E/",
    "https://emvlab.org/emvtags/show/t5F53/",
    "https://emvlab.org/emvtags/show/t9F0D/",
    "https://emvlab.org/emvtags/show/t9F0E/",
    "https://emvlab.org/emvtags/show/t9F0F/",
    "https://emvlab.org/emvtags/show/t9F10/",
    "https://emvlab.org/emvtags/show/t91/",
    "https://emvlab.org/emvtags/show/t9F11/",
    "https://emvlab.org/emvtags/show/t5F28/",
    "https://emvlab.org/emvtags/show/t5F55/",
    "https://emvlab.org/emvtags/show/t5F56/",
    "https://emvlab.org/emvtags/show/t42/",
    "https://emvlab.org/emvtags/show/t90/",
    "https://emvlab.org/emvtags/show/t9F32/",
    "https://emvlab.org/emvtags/show/t92/",
    "https://emvlab.org/emvtags/show/t86/",
    "https://emvlab.org/emvtags/show/t9F18/",
    "https://emvlab.org/emvtags/show/t71/",
    "https://emvlab.org/emvtags/show/t72/",
    "https://emvlab.org/emvtags/show/t5F50/",
    "https://emvlab.org/emvtags/show/t5F2D/",
    "https://emvlab.org/emvtags/show/t9F13/",
    "https://emvlab.org/emvtags/show/t9F4D/",
    "https://emvlab.org/emvtags/show/t9F4F/",
    "https://emvlab.org/emvtags/show/t9F14/",
    "https://emvlab.org/emvtags/show/t9F15/",
    "https://emvlab.org/emvtags/show/t9F16/",
    "https://emvlab.org/emvtags/show/t9F4E/",
    "https://emvlab.org/emvtags/show/t9F17/",
    "https://emvlab.org/emvtags/show/t9F39/",
    "https://emvlab.org/emvtags/show/t9F38/",
    "https://emvlab.org/emvtags/show/t80/",
    "https://emvlab.org/emvtags/show/t77/",
    "https://emvlab.org/emvtags/show/t5F30/",
    "https://emvlab.org/emvtags/show/t88/",
    "https://emvlab.org/emvtags/show/t9F4B/",
    "https://emvlab.org/emvtags/show/t93/",
    "https://emvlab.org/emvtags/show/t9F4A/",
    "https://emvlab.org/emvtags/show/t9F33/",
    "https://emvlab.org/emvtags/show/t9F1A/",
    "https://emvlab.org/emvtags/show/t9F1B/",
    "https://emvlab.org/emvtags/show/t9F1C/",
    "https://emvlab.org/emvtags/show/t9F1D/",
    "https://emvlab.org/emvtags/show/t9F35/",
    "https://emvlab.org/emvtags/show/t95/",
    "https://emvlab.org/emvtags/show/t9F1F/",
    "https://emvlab.org/emvtags/show/t9F20/",
    "https://emvlab.org/emvtags/show/t57/",
    "https://emvlab.org/emvtags/show/t98/",
    "https://emvlab.org/emvtags/show/t97/",
    "https://emvlab.org/emvtags/show/t5F2A/",
    "https://emvlab.org/emvtags/show/t5F36/",
    "https://emvlab.org/emvtags/show/t9A/",
    "https://emvlab.org/emvtags/show/t99/",
    "https://emvlab.org/emvtags/show/t9F3C/",
    "https://emvlab.org/emvtags/show/t9F3D/",
    "https://emvlab.org/emvtags/show/t9F41/",
    "https://emvlab.org/emvtags/show/t9B/",
    "https://emvlab.org/emvtags/show/t9F21/",
    "https://emvlab.org/emvtags/show/t9C/",
    "https://emvlab.org/emvtags/show/t9F37/",
    "https://emvlab.org/emvtags/show/t9F23/"]


def get_data():
    x = dict()
    for key, msg, url in zip(tags, msgs, urls):
        x[key] = [msg, url]
    return x


countries = [
    "Åland Islands",
    "Antarctica",
    "Anguilla",
    "Antigua and Barbuda",
    "Aruba",
    "United States Minor Outlying Islands",
    "Barbados",
    "Belize",
    "Bermuda",
    "Bonaire",
    "Bosnia and Herzegovina",
    "Bouvet Island",
    "Burkina Faso",
    "Canada",
    "French Polynesia",
    "Georgia",
    "Gibraltar",
    "Grenada",
    "Guadeloupe",
    "French Guiana",
    "Hungary",
    "Iceland",
    "Ireland",
    "Jamaica",
    "Japan",
    "Greenland",
    "Malaysia",
    "Martinique",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "New Caledonia",
    "New Zealand",
    "Niue",
    "Réunion",
    "Romania",
    "Saint Helena",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Sint Eustatius – See Bonaire, Sint Eustatius and Saba.",
    "Sint Maarten (Dutch part)",
    "South Georgia and the South Sandwich Islands",
    "Svalbard",
    "Egypt",
    "Argentina",
    "Guernsey",
    "Jersey",
    "Venezuela",
    "British Indian Ocean Territory",
    "Cayman Islands",
    "Central African Republic",
    "Guyana",
    "Saint Barthélemy",
    "Saint Martin (French part)",
    "Australia",
    "Dominica",
    "Puerto Rico",
    "Bahamas",
    "Northern Mariana Islands",
    "Cook Islands",
    "Curaçao",
    "Czechia",
    "Korea",
    "Sao Tome and Principe",
    "Congo",
    "Timor-Leste",
    "Sri Lanka",
    "Mayotte",
    "Dominican Republic",
    "Falkland Islands",
    "Faroe Islands",
    "Ethiopia",
    "Nepal",
    "Germany",
    "Nigeria",
    "Somalia",
    "Micronesia",
    "Brazil",
    "France",
    "French Southern Territories",
    "Gabon",
    "Luxembourg",
    "Jordan",
    "Greece",
    "Holy See",
    "Hong Kong",
    "Papua New Guinea",
    "Samoa",
    "Afghanistan",
    "Iran",
    "Mauritania",
    "Pakistan",
    "Isle of Man",
    "Italy",
    "Bahrain",
    "Belgium",
    "Bhutan",
    "Cambodia",
    "Denmark",
    "Eswatini",
    "Lesotho",
    "Morocco",
    "Norway",
    "Saudi Arabia",
    "Spain",
    "Sweden",
    "Thailand",
    "Netherlands",
    "Tonga",
    "Kyrgyzstan",
    "Lao People's Democratic Republic",
    "Lebanon",
    "Macao",
    "Brunei Darussalam",
    "Uruguay",
    "Saint Pierre and Miquelon",
    "Algeria",
    "Bangladesh",
    "China",
    "Pitcairn",
    "Bolivia",
    "Portugal",
    "Andorra",
    "Liechtenstein",
    "Monaco",
    "Albania",
    "Angola",
    "Armenia",
    "Austria",
    "Azerbaijan",
    "Belarus",
    "Benin",
    "Botswana",
    "Bulgaria",
    "Burundi",
    "Cabo Verde",
    "Cameroon",
    "Chad",
    "Chile",
    "Taiwan",
    "Colombia",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Djibouti",
    "Ecuador",
    "El Salvador",
    "Equatorial Guinea",
    "Estonia",
    "Fiji",
    "Finland",
    "Ghana",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Haiti",
    "Honduras",
    "India",
    "Indonesia",
    "Iraq",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea",
    "Latvia",
    "Liberia",
    "Lithuania",
    "Madagascar",
    "Malawi",
    "Maldives",
    "Mali",
    "Malta",
    "Mauritius",
    "Moldova",
    "Mozambique",
    "Namibia",
    "Nauru",
    "Nicaragua",
    "North Macedonia",
    "Palau",
    "Panama",
    "Paraguay",
    "Peru",
    "Poland",
    "Rwanda",
    "San Marino",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovenia",
    "South Africa",
    "South Sudan",
    "Suriname",
    "Tajikistan",
    "Congo",
    "Gambia",
    "Marshall Islands",
    "Niger",
    "Philippines",
    "Sudan",
    "Myanmar",
    "Trinidad and Tobago",
    "Tunisia",
    "Türkiye",
    "Uganda",
    "Uzbekistan",
    "Vanuatu",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    "Russian Federation",
    "Western Sahara ",
    "Slovakia",
    "Viet Nam ",
    "Solomon Islands",
    "Eritrea",
    "Israel",
    "Kuwait",
    "Libya",
    "Palestine, State of",
    "Qatar",
    "Oman",
    "Switzerland",
    "Syrian Arab Republic",
    "American Samoa",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Guam",
    "Heard Island and McDonald Islands",
    "Norfolk Island",
    "Wallis and Futuna",
    "Togo",
    "Turks and Caicos Islands",
    "Comoros",
    "United Arab Emirates",
    "United Kingdom of Great Britain and Northern Ireland",
    "Mexico",
    "Tanzania, the United Republic of",
    "United States of America",
    "Virgin Islands",
    "Virgin Islands",
    "Tokelau",
    "Turkmenistan",
    "Tuvalu",
    "Ukraina"]


countries_number = [
    "0248",
    "0010",
    "0660",
    "0028",
    "0533",
    "0581",
    "0052",
    "0084",
    "0060",
    "0535",
    "0070",
    "0074",
    "0854",
    "0124",
    "0258",
    "0268",
    "0292",
    "0308",
    "0312",
    "0254",
    "0348",
    "0352",
    "0372",
    "0388",
    "0392",
    "0304",
    "0458",
    "0474",
    "0496",
    "0499",
    "0500",
    "0540",
    "0554",
    "0570",
    "0638",
    "0642",
    "0654",
    "0659",
    "0662",
    "0000",
    "0534",
    "0239",
    "0744",
    "0818",
    "0032",
    "0831",
    "0832",
    "0862",
    "0086",
    "0136",
    "0140",
    "0328",
    "0652",
    "0663",
    "0036",
    "0212",
    "0630",
    "0044",
    "0580",
    "0184",
    "0531",
    "0203",
    "0408",
    "0678",
    "0180",
    "0626",
    "0144",
    "0175",
    "0214",
    "0238",
    "0234",
    "0231",
    "0524",
    "0276",
    "0566",
    "0706",
    "0583",
    "0076",
    "0250",
    "0260",
    "0266",
    "0442",
    "0400",
    "0300",
    "0336",
    "0344",
    "0598",
    "0882",
    "0004",
    "0364",
    "0478",
    "0586",
    "0833",
    "0380",
    "0048",
    "0056",
    "0064",
    "0116",
    "0208",
    "0748",
    "0426",
    "0504",
    "0578",
    "0682",
    "0724",
    "0752",
    "0764",
    "0528",
    "0776",
    "0417",
    "0418",
    "0422",
    "0446",
    "0096",
    "0858",
    "0666",
    "0012",
    "0050",
    "0156",
    "0612",
    "0068",
    "0620",
    "0020",
    "0438",
    "0492",
    "0008",
    "0024",
    "0051",
    "0040",
    "0031",
    "0112",
    "0204",
    "0072",
    "0100",
    "0108",
    "0132",
    "0120",
    "0148",
    "0152",
    "0158",
    "0170",
    "0188",
    "0384",
    "0191",
    "0192",
    "0196",
    "0262",
    "0218",
    "0222",
    "0226",
    "0233",
    "0242",
    "0246",
    "0288",
    "0320",
    "0324",
    "0624",
    "0332",
    "0340",
    "0356",
    "0360",
    "0368",
    "0398",
    "0404",
    "0296",
    "0410",
    "0428",
    "0430",
    "0440",
    "0450",
    "0454",
    "0462",
    "0466",
    "0470",
    "0480",
    "0498",
    "0508",
    "0516",
    "0520",
    "0558",
    "0807",
    "0585",
    "0591",
    "0600",
    "0604",
    "0616",
    "0646",
    "0674",
    "0686",
    "0688",
    "0690",
    "0694",
    "0702",
    "0705",
    "0710",
    "0728",
    "0740",
    "0762",
    "0178",
    "0270",
    "0584",
    "0562",
    "0608",
    "0729",
    "0104",
    "0780",
    "0788",
    "0792",
    "0800",
    "0860",
    "0548",
    "0887",
    "0894",
    "0716",
    "0643",
    "0732",
    "0703",
    "0704",
    "0090",
    "0232",
    "0376",
    "0414",
    "0434",
    "0275",
    "0634",
    "0512",
    "0756",
    "0760",
    "0016",
    "0162",
    "0166",
    "0316",
    "0334",
    "0574",
    "0876",
    "0768",
    "0796",
    "0174",
    "0784",
    "0826",
    "0484",
    "0834",
    "0840",
    "0092",
    "0850",
    "0772",
    "0795",
    "0798",
    "0804"
]


def get_countries():
    output = dict()
    for number, country in zip(countries_number, countries):
        output[number] = country
    return output
